name: Run tests

on:
  push:
    branches:
      - "gh_actions_dev"
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
#  lint:
#    runs-on: ubuntu-latest
#    continue-on-error: true
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python 3.9
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#      - name: Linting
#        run: |
#          pip install pre-commit
#          pre-commit run --all-files
  test:
    name: Test on Linux, Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    # More info on options: https://github.com/goanpeca/setup-miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        activate-environment: hamsm_env
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

    - name: Install package
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        conda info --all
        python -m pip install .[tests]
        conda list
    - name: Run tests
      # conda setup requires this special shell
      shell: bash -l {0}
      run: |
        pytest -v --color=yes --capture=no --log-cli-level INFO
